STRINGS = {
    "zh": {
        "app_title": "封面预览生成器",
        "menu_file": "文件",
        "menu_open": "打开图片",
        "menu_exit": "退出",
        "menu_language": "语言",
        "menu_lang_zh": "中文",
        "menu_lang_en": "English",
        "menu_help": "帮助",
        "menu_about": "关于",
        "about_text": "封面预览生成器\nMIT License\n© KyotoMiyaChan 2026",
        "btn_browse": "浏览",
        "placeholder_img": "选择图片...",
        "label_text": "文字:",
        "label_font": "字体:",
        "label_scale": "缩放:",
        "label_size": "字号:",
        "label_opacity": "不透明度:",
        "label_rotation": "旋转:",
        "label_preview": "预览",
        "label_color": "颜色:",
        "tooltip_pick_color": "选取水印颜色",
        "dialog_pick_color": "选择水印颜色",
        "btn_generate": "生成",
        "btn_copy": "复制",
        "btn_open": "打开目录",
        "status_ready": "就绪",
        "status_saved": "已保存: {}",
        "status_invalid": "请先选择图片",
        "status_open_fail": "无法打开图片: {}",
        "status_gen_fail": "生成失败: {}",
        "status_copied": "已复制到剪贴板",
        "status_copy_fail": "复制失败: {}",
        "footer_copyright": "© KyotoMiyaChan 2026 ｜",
        "footer_repo": "点我访问仓库",
        "footer_star": "｜ 本软件开源免费，点个star支持一下吧",
    },
    "en": {
        "app_title": "Cover Preview Generator",
        "menu_file": "File",
        "menu_open": "Open Image",
        "menu_exit": "Exit",
        "menu_language": "Language",
        "menu_lang_zh": "中文",
        "menu_lang_en": "English",
        "menu_help": "Help",
        "menu_about": "About",
        "about_text": "Cover Preview Generator\nMIT License\n© KyotoMiyaChan 2026",
        "btn_browse": "Browse",
        "placeholder_img": "Select image...",
        "label_text": "Text:",
        "label_font": "Font:",
        "label_scale": "Scale:",
        "label_size": "Size:",
        "label_opacity": "Opacity:",
        "label_rotation": "Rotation:",
        "label_preview": "Preview",
        "label_color": "Color:",
        "tooltip_pick_color": "Pick watermark color",
        "dialog_pick_color": "Choose Watermark Color",
        "btn_generate": "Generate",
        "btn_copy": "Copy",
        "btn_open": "Open Folder",
        "status_ready": "Ready",
        "status_saved": "Saved: {}",
        "status_invalid": "Please select an image first",
        "status_open_fail": "Cannot open image: {}",
        "status_gen_fail": "Generation failed: {}",
        "status_copied": "Copied to clipboard",
        "status_copy_fail": "Copy failed: {}",
        "footer_copyright": "© KyotoMiyaChan 2026 |",
        "footer_repo": "Visit Repository",
        "footer_star": "| Free & Open Source, Star us!",
    }
}
